# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='demo',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ndata.proto\x12\x04\x64\x65mo\"\x14\n\x04\x64\x61ta\x12\x0c\n\x04text\x18\x02 \x01(\t2/\n\tAddNumber\x12\"\n\x06\x64o_add\x12\n.demo.data\x1a\n.demo.data\"\x00\x62\x06proto3')
)




_DATA = _descriptor.Descriptor(
  name='data',
  full_name='demo.data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='demo.data.text', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=40,
)

DESCRIPTOR.message_types_by_name['data'] = _DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

data = _reflection.GeneratedProtocolMessageType('data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:demo.data)
  ))
_sym_db.RegisterMessage(data)



_ADDNUMBER = _descriptor.ServiceDescriptor(
  name='AddNumber',
  full_name='demo.AddNumber',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=42,
  serialized_end=89,
  methods=[
  _descriptor.MethodDescriptor(
    name='do_add',
    full_name='demo.AddNumber.do_add',
    index=0,
    containing_service=None,
    input_type=_DATA,
    output_type=_DATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADDNUMBER)

DESCRIPTOR.services_by_name['AddNumber'] = _ADDNUMBER

# @@protoc_insertion_point(module_scope)
