# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import data_pb2 as data__pb2


class AddNumberStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.do_add = channel.unary_unary(
        '/demo.AddNumber/do_add',
        request_serializer=data__pb2.data.SerializeToString,
        response_deserializer=data__pb2.data.FromString,
        )


class AddNumberServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def do_add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AddNumberServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'do_add': grpc.unary_unary_rpc_method_handler(
          servicer.do_add,
          request_deserializer=data__pb2.data.FromString,
          response_serializer=data__pb2.data.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'demo.AddNumber', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
